/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package exambr;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
//import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.Date;

/**
 *
 * @author Njuguna
 */
public class Form2_JFrame extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst =null;
    //JButton cal,clr;
    //JTextField val_1,val_2,val_3,val_4,val_5,val_6,val_7,val_8,val_9,val_10,val_11,val_12,itr;
    //JTextField1 itr;
    int sum=0,total_sum=0,a=0,b=0,c=0,d=0, n = 0 ,f=0,g=0,h=0,i=0,j=0,k=0,l=0,m=0;
    int avg=0;
    char grades;
    /**
     * Creates new form Form2_JFrame
     */
    public Form2_JFrame() {
        initComponents();
        conn =javaconnect.ConnecrDb();
        Update_Table();
        cal.action(null, this);
        txt_grade.action(null, this);
        //cal.addActionListener(this);
    }
    
    private void Update_Table(){
        
          try {
            
            String sql = "SELECT id,firstname,lastname,maths,english,biology,chem,hist,agri,cre,comp,art,bizstudies,total,avg,grade from subjects ";
                   
        pst = conn.prepareStatement(sql);
        rs =pst.executeQuery(sql);
        sub_table.setModel(DbUtils.resultSetToTableModel(rs));
        
         
        } catch (Exception exp) {
            JOptionPane.showMessageDialog(null, exp);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_ind = new javax.swing.JTextField();
        txt_fn = new javax.swing.JTextField();
        txt_ln = new javax.swing.JTextField();
        val_1 = new javax.swing.JTextField();
        val_2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        sub_table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        val_3 = new javax.swing.JTextField();
        val_4 = new javax.swing.JTextField();
        val_5 = new javax.swing.JTextField();
        val_6 = new javax.swing.JTextField();
        val_7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        val_8 = new javax.swing.JTextField();
        val_9 = new javax.swing.JTextField();
        val_10 = new javax.swing.JTextField();
        cmd_save = new javax.swing.JButton();
        itr1 = new javax.swing.JTextField();
        cal = new javax.swing.JButton();
        itr = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_grade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        clr = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        itr3 = new javax.swing.JLabel();
        report_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("INDEX NUMBER");

        jLabel2.setText("FIRST NAME");

        jLabel3.setText("LAST NAME");

        jLabel4.setText("MATHS");

        jLabel5.setText("ENGLISH");

        txt_ind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_indActionPerformed(evt);
            }
        });

        txt_fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnActionPerformed(evt);
            }
        });

        val_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_1ActionPerformed(evt);
            }
        });

        val_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_2ActionPerformed(evt);
            }
        });

        sub_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(sub_table);

        jLabel6.setText("BIOLOGY");

        jLabel7.setText("CHEMISTRY");

        jLabel8.setText("HISTORY");

        jLabel9.setText("AGRICULTURE");

        jLabel10.setText("C.R.E");

        jLabel11.setText("COMPUTER");

        val_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_3ActionPerformed(evt);
            }
        });

        val_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_4ActionPerformed(evt);
            }
        });

        val_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_5ActionPerformed(evt);
            }
        });

        val_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_6ActionPerformed(evt);
            }
        });

        val_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_7ActionPerformed(evt);
            }
        });

        jLabel12.setText("ART");

        jLabel13.setText("BUSINESS STUDIES");

        val_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_8ActionPerformed(evt);
            }
        });

        val_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_9ActionPerformed(evt);
            }
        });

        val_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_10ActionPerformed(evt);
            }
        });

        cmd_save.setText("SAVE");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });

        itr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itr1ActionPerformed(evt);
            }
        });

        cal.setText("CALCULATE");
        cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calActionPerformed(evt);
            }
        });

        jLabel14.setText("TOTAL MARKS");

        jLabel15.setText("AVERAGE");

        txt_grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gradeActionPerformed(evt);
            }
        });

        jLabel16.setText("GRADE");

        clr.setText("CLEAR");

        jLabel17.setBackground(new java.awt.Color(51, 51, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("BRIAN EXAM SYSTEM");

        jLabel18.setText("TOTAL MARKS");

        report_jButton.setText("REPORTS");
        report_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_ln)
                                    .addComponent(val_2)
                                    .addComponent(val_1)
                                    .addComponent(txt_fn)
                                    .addComponent(txt_ind)
                                    .addComponent(val_3)
                                    .addComponent(val_4)
                                    .addComponent(val_5)
                                    .addComponent(val_6)
                                    .addComponent(val_7)
                                    .addComponent(val_8)
                                    .addComponent(val_9, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(val_10, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))))
                    .addComponent(jLabel17))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cal, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(clr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(report_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(87, 87, 87)
                                .addComponent(jLabel16))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(itr, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(itr1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmd_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(itr3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_ind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(val_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(val_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(val_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(val_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(val_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(val_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(val_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(val_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(itr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(itr3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(report_jButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(val_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(cal)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(val_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmd_save)
                        .addComponent(clr)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnActionPerformed

    private void val_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_2ActionPerformed
        // TODO add your handling code here:
        System.out.println(a);
    }//GEN-LAST:event_val_2ActionPerformed

    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Insert into subjects ( id,firstname, lastname, maths, english, biology, chem, hist, bizstudies, agri, cre, comp, art,total,avg,grade) value (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)  ";
            pst = conn.prepareStatement(sql);
            pst.setString(1,txt_ind.getText());
            pst.setString(2,txt_fn.getText());
            pst.setString(3,txt_ln.getText());
            pst.setString(4,val_1.getText());
            pst.setString(5,val_2.getText());
            pst.setString(6,val_3.getText());
            pst.setString(7,val_4.getText());
            pst.setString(8,val_5.getText());
            pst.setString(9,val_6.getText());
            pst.setString(10,val_7.getText());
            pst.setString(11,val_8.getText());
            pst.setString(12,val_9.getText());
            pst.setString(13,val_10.getText());
            pst.setString(14,itr.getText());
            pst.setString(15,itr1.getText());
            pst.setString(16, txt_grade.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "****************************\nMarks Saved Successfully\n****************************\n");
        } catch (Exception ex) {                                 
            JOptionPane.showMessageDialog(null, ex);
        }
        Update_Table();
    }//GEN-LAST:event_cmd_saveActionPerformed

    private void txt_indActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_indActionPerformed
        // TODO add your handling code here:
        itr.setEditable(false);
    }//GEN-LAST:event_txt_indActionPerformed

    private void itr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itr1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_itr1ActionPerformed

    private void calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calActionPerformed
        // TODO add your handling code here:
        
        
        	try
		{
			if(cal==evt.getSource())
			{
a=Integer.parseInt(val_1.getText());
b=Integer.parseInt(val_2.getText());
c=Integer.parseInt(val_3.getText());
d=Integer.parseInt(val_4.getText());
n=Integer.parseInt(val_5.getText());
f=Integer.parseInt(val_6.getText());
g=Integer.parseInt(val_7.getText());
h=Integer.parseInt(val_7.getText());
i=Integer.parseInt(val_8.getText());
j=Integer.parseInt(val_9.getText());
k=Integer.parseInt(val_10.getText());
//l=Integer.parseInt(val_11.getText());
//m=Integer.parseInt(val_12.getText());
//b=Integer.parseInt(val_2.getText());
//total_sum=(a + b + c + d + e + f + g + h + i + j + k + l + m + );

total_sum = (a+b+c+d+n+f+g+h+i+j+k+l+m);
//avg = (a+b+c+d+n+f+g+h+i+j)/10;
avg = total_sum/10;
itr.setText(Integer.toString(total_sum));
itr1.setText(Integer.toString(avg));
//itr3.setText(Integer.toString(total_sum));
			}
			else if(clr==evt.getSource()){
				val_1.setText("");
				val_2.setText("");
                                val_3.setText("");
                                val_4.setText("");
                                val_5.setText("");
                                val_6.setText("");
                                val_7.setText("");
                                val_8.setText("");
                                val_9.setText("");
                                val_10.setText("");
//                              val_11.setText("");
//                              val_12.setText("");
				itr.setText("");
                                itr1.setText("");
                                //itr3.setText("");
			}
                        
                        
		}
                
                
		catch(NumberFormatException num){
			val_1.setText("0");
			val_2.setText("0");
                        val_3.setText("0");
                        val_4.setText("0");
                        val_5.setText("0");
                        val_6.setText("0");
                        val_7.setText("0");
                        val_8.setText("0");
                        val_9.setText("0");
                        val_10.setText("0");
//                      val_11.setText("0");
//                      val_12.setText("0");
			itr.setText("0");
                        itr1.setText("0");
		}
                catch(Exception ex){
                    ex.printStackTrace();
               }
                
              
         try {
            
              
            
             if (avg>=0 && avg <= 100){
                 avg = total_sum/10;
                 //avg = (a+b+c+d+n+f+g+h+i+j)/10;
        //txt_grade.setText(char.class.toString());
             // txt_grade.setText(char.class.getName());
              //txt_grade.setText(Character.toString(grades));
            //int marks = 0;
            
            if (avg>=70)
            grades = 'A';
        else if (avg>=60)
            grades = 'B';
        else if (avg>=50)
            grades = 'C';
        else if (avg>=40)
            grades = 'D';
        else  
            grades = 'E';
       
       System.out.println("maths :" +a);
       System.out.println("english :" +b);
       System.out.println("biology :" +c);
       System.out.println("chem :" +d);
       System.out.println("histo :" +n);
       System.out.println("agric :" +f);
       System.out.println("cre :" +g);
       System.out.println("computer :" +h);
       System.out.println("art :" +i);
       System.out.println("business :" +j);
       
       txt_grade.setText(Character.toString(grades));
       System.out.println("\n the average mark is:  " +avg);
       System.out.println("\n the grade obtained is:  " +grades);
       //JOptionPane.showMessageDialog(null,"****************************\nGRADE SCORED IS:"+grades+"\n****************************\n");    
            
        }  else
            System.out.println(avg +" is an invalid mark\n");
            System.out.println(avg+ " is a valid mark\n");
   
            
        } catch (Exception e) {
            e.getStackTrace();
        }        
        
        
        
//        if (rootPaneCheckingEnabled) {
//            
//        }
    }//GEN-LAST:event_calActionPerformed

    private void txt_gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gradeActionPerformed
        // TODO add your handling code here:
        
//        try {
//            
//              avg = (a+b+c+d+n+f+g+h+i+j)/10;
//        txt_grade.setText(Integer.toString(avg));
//            
//             if (avg>=0 && avg <= 100){
//            
//            if (avg>=70)
//            grades = 'A';
//        else if (avg>=60)
//            grades = 'B';
//        else if (avg>=50)
//            grades = 'C';
//        else if (avg>=40)
//            grades = 'D';
//        else  
//            grades = 'E';
//        
//       System.out.println("\n the average mark is:  " +avg);
//       System.out.println("\n the grade obtained is:  " +grades);
//            
//            
//        }
//            
//        } catch (Exception e) {
//            e.getStackTrace();
//        }
//        avg = (a+b+c+d+n+f+g+h+i+j)/10;
//        txt_grade.setText(Integer.toString(avg));
        
       
    }//GEN-LAST:event_txt_gradeActionPerformed

    private void val_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_1ActionPerformed
        // TODO add your handling code here:
        System.out.println();
    }//GEN-LAST:event_val_1ActionPerformed

    private void val_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_3ActionPerformed
        // TODO add your handling code here:
        System.out.println(b);
    }//GEN-LAST:event_val_3ActionPerformed

    private void val_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_4ActionPerformed
        // TODO add your handling code here:
        System.out.println(c);
    }//GEN-LAST:event_val_4ActionPerformed

    private void val_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_5ActionPerformed
        // TODO add your handling code here:
        System.out.println(d);
    }//GEN-LAST:event_val_5ActionPerformed

    private void val_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_6ActionPerformed
        // TODO add your handling code here:
        System.out.println(n);
    }//GEN-LAST:event_val_6ActionPerformed

    private void val_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_7ActionPerformed
        // TODO add your handling code here:
        System.out.println(f);
    }//GEN-LAST:event_val_7ActionPerformed

    private void val_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_8ActionPerformed
        // TODO add your handling code here:
        System.out.println(g);
    }//GEN-LAST:event_val_8ActionPerformed

    private void val_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_9ActionPerformed
        // TODO add your handling code here:
        System.out.println(h);
    }//GEN-LAST:event_val_9ActionPerformed

    private void val_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_10ActionPerformed
        // TODO add your handling code here:
        System.out.println(i);
    }//GEN-LAST:event_val_10ActionPerformed

    private void report_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_jButtonActionPerformed
        // TODO add your handling code here:
        
        
        String Value_1 = txt_ind.getText();
        String value_2 =txt_fn.getText();
        String value_3 =txt_ln.getText();
//        String value_4 =txt_fn.getText();
        String value_4 =val_1.getText();
        String value_5 =val_2.getText();
        String value_6 =val_3.getText();
        String value_7 =val_4.getText();
        String value_8 =val_5.getText();
        String value_9 =val_6.getText();
        String value_10 =val_7.getText();
        String value_11 =val_8.getText();
        String value_12 =val_9.getText();
        String value_13 =val_10.getText();
        String value_14 =itr.getText();
        String value_15 =itr1.getText();
        
        String value_16;
        value_16 = txt_grade.getText();
                 //txt_grade.setText(Character.toString(grades));
        try {
            
           Document document = new Document();
        PdfWriter.getInstance(document,new FileOutputStream("report.pdf"));
        document.open();
        
        document.add(new Paragraph("*********************************************************************\n"));
        document.add(new Paragraph(new Date().toString()));
        document.add(new Paragraph("**********************************************************************\n"));
            PdfPTable table = new PdfPTable(2);
            PdfPCell cell   = new PdfPCell(new Paragraph("title"));
            cell.setColspan(4);
            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setBackgroundColor(BaseColor.BLUE);
            
            table.addCell(cell);
            
            table.addCell("INDEX NO");
            table.addCell(Value_1);
            cell.setBackgroundColor(BaseColor.BLUE);
            table.addCell("FIRST NAME");
            table.addCell(value_2);
            table.addCell("LAST NAME");
            table.addCell(value_3);
            table.addCell("MATHS");
            table.addCell(value_4);
            table.addCell("ENGLISH");
            table.addCell(value_5);
            table.addCell("BIOLOGY");
            table.addCell(value_6);
            table.addCell("CHEMISTRY");
            table.addCell(value_7);
            table.addCell("HISTORY");
            table.addCell(value_8);
            table.addCell("AGRICULTURE");
            table.addCell(value_9);
            table.addCell("CRE");
            table.addCell(value_10);
            table.addCell("COMPUTER");
            table.addCell(value_11);
            table.addCell("ART");
            table.addCell(value_12);
            table.addCell("BUSINESS STUDIES");
            table.addCell(value_13);
            table.addCell("TOTAL MARKS");
            table.addCell(value_14);
            table.addCell("AVERAGE");
            table.addCell(value_15);
            table.addCell("GRADE");
            table.addCell(value_16);
            
            document.add(table);
            com.itextpdf.text.List list = new com.itextpdf.text.List(true,20);
//            list.add("1st item ");
//            list.add("1st item ");
//            list.add("1st item ");
//            list.add("1st item ");
            
            document.add(list);
        document.close();
        JOptionPane.showMessageDialog(null,"report saved");
        
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
       
    }//GEN-LAST:event_report_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form2_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form2_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form2_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form2_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form2_JFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cal;
    private javax.swing.JButton clr;
    private javax.swing.JButton cmd_save;
    private javax.swing.JTextField itr;
    private javax.swing.JTextField itr1;
    private javax.swing.JLabel itr3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton report_jButton;
    private javax.swing.JTable sub_table;
    private javax.swing.JTextField txt_fn;
    private javax.swing.JTextField txt_grade;
    private javax.swing.JTextField txt_ind;
    private javax.swing.JTextField txt_ln;
    private javax.swing.JTextField val_1;
    private javax.swing.JTextField val_10;
    private javax.swing.JTextField val_2;
    private javax.swing.JTextField val_3;
    private javax.swing.JTextField val_4;
    private javax.swing.JTextField val_5;
    private javax.swing.JTextField val_6;
    private javax.swing.JTextField val_7;
    private javax.swing.JTextField val_8;
    private javax.swing.JTextField val_9;
    // End of variables declaration//GEN-END:variables
}
