/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package exambr;

/**
 *
 * @author MENTY
 */
public class mainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    public mainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmd_f1 = new javax.swing.JButton();
        cmd_f2 = new javax.swing.JButton();
        cmd_f3 = new javax.swing.JButton();
        cmd_f4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmd_f1.setText("FORM ONE");
        cmd_f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_f1ActionPerformed(evt);
            }
        });

        cmd_f2.setText("FORM TWO ");
        cmd_f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_f2ActionPerformed(evt);
            }
        });

        cmd_f3.setText("FORM THREE");

        cmd_f4.setText("FORM FOUR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmd_f2)
                        .addGap(18, 18, 18)
                        .addComponent(cmd_f4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmd_f1)
                        .addGap(18, 18, 18)
                        .addComponent(cmd_f3)))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_f1)
                    .addComponent(cmd_f3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_f2)
                    .addComponent(cmd_f4))
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_f1ActionPerformed
        // TODO add your handling code here:
        
        
        try {
            
             Form1_JFrame s = new  Form1_JFrame();
                s.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cmd_f1ActionPerformed

    private void cmd_f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_f2ActionPerformed
        // TODO add your handling code here:
        
        try {
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cmd_f2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
                //new Students_jpanel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_f1;
    private javax.swing.JButton cmd_f2;
    private javax.swing.JButton cmd_f3;
    private javax.swing.JButton cmd_f4;
    // End of variables declaration//GEN-END:variables
}
